<?php

/*
|--------------------------------------------------------------------------
| AI: Attend Mo
| Analytics Report Data Reader
|--------------------------------------------------------------------------
| Reads CSV reports generated by the Python analytics pipeline.
|--------------------------------------------------------------------------
*/


// ============================================================
// 1. PROJECT PATHS
// ============================================================

$projectRoot = dirname(__DIR__, 2);

$reportsPath =
    $projectRoot
    . DIRECTORY_SEPARATOR
    . "reports";


// ============================================================
// 2. GENERAL CSV READER
// ============================================================

function readCsvRows($filePath)
{
    if (!file_exists($filePath)) {
        return [];
    }

    $handle = fopen($filePath, "r");

    if ($handle === false) {
        return [];
    }

    $headers = fgetcsv($handle);

    if ($headers === false) {
        fclose($handle);
        return [];
    }

    if (isset($headers[0])) {
        $headers[0] = preg_replace(
            '/^\xEF\xBB\xBF/',
            '',
            trim($headers[0])
        );
    }

    $headers = array_map(
        "trim",
        $headers
    );

    $rows = [];

    while (($data = fgetcsv($handle)) !== false) {

        if (count($data) !== count($headers)) {
            continue;
        }

        $row = array_combine(
            $headers,
            $data
        );

        if ($row !== false) {
            $rows[] = array_map(
                "trim",
                $row
            );
        }
    }

    fclose($handle);

    return $rows;
}


// ============================================================
// 3. METRIC / VALUE CSV READER
// ============================================================

function readMetricValueCsv($filePath)
{
    if (!file_exists($filePath)) {
        return [];
    }

    $handle = fopen($filePath, "r");

    if ($handle === false) {
        return [];
    }

    // Skip Metric,Value header
    fgetcsv($handle);

    $metrics = [];

    while (($row = fgetcsv($handle)) !== false) {

        if (count($row) < 2) {
            continue;
        }

        $metric = trim(
            preg_replace(
                '/^\xEF\xBB\xBF/',
                '',
                $row[0]
            )
        );

        $value = trim($row[1]);

        if ($metric !== "") {
            $metrics[$metric] = $value;
        }
    }

    fclose($handle);

    return $metrics;
}


// ============================================================
// 4. OVERALL ATTENDANCE SUMMARY
// ============================================================

$overallFile =
    $reportsPath
    . DIRECTORY_SEPARATOR
    . "overall_attendance_summary.csv";

$overallMetrics =
    readMetricValueCsv(
        $overallFile
    );


$totalStudentsRaw =
    $overallMetrics["Total Students"]
    ?? null;

$totalAttendanceRecordsRaw =
    $overallMetrics["Total Attendance Records"]
    ?? null;

$totalPresentRaw =
    $overallMetrics["Total Present"]
    ?? null;

$totalAbsentRaw =
    $overallMetrics["Total Absent"]
    ?? null;

$attendanceRateRaw =
    $overallMetrics["Overall Attendance Rate"]
    ?? null;

$absenceRateRaw =
    $overallMetrics["Overall Absence Rate"]
    ?? null;


// ============================================================
// 5. FORMAT OVERALL VALUES
// ============================================================

$totalStudents =
    is_numeric($totalStudentsRaw)
        ? (int)$totalStudentsRaw
        : "—";

$totalAttendanceRecords =
    is_numeric($totalAttendanceRecordsRaw)
        ? (int)$totalAttendanceRecordsRaw
        : "—";

$totalPresent =
    is_numeric($totalPresentRaw)
        ? (int)$totalPresentRaw
        : "—";

$totalAbsent =
    is_numeric($totalAbsentRaw)
        ? (int)$totalAbsentRaw
        : "—";


if (is_numeric($attendanceRateRaw)) {

    $attendanceRate =
        number_format(
            ((float)$attendanceRateRaw) * 100,
            2
        ) . "%";

} else {

    $attendanceRate = "—";
}


if (is_numeric($absenceRateRaw)) {

    $absenceRate =
        number_format(
            ((float)$absenceRateRaw) * 100,
            2
        ) . "%";

} else {

    $absenceRate = "—";
}


// ============================================================
// 6. DAILY ATTENDANCE TREND
// ============================================================

$dailyTrendFile =
    $reportsPath
    . DIRECTORY_SEPARATOR
    . "daily_attendance_trend.csv";


$dailyTrendRows =
    readCsvRows(
        $dailyTrendFile
    );


$dailyTrend = [];


foreach ($dailyTrendRows as $row) {

    $date =
        $row["Date"]
        ?? "";

    $rate =
        $row["Attendance_Rate"]
        ?? null;


    if (
        $date === ""
        ||
        !is_numeric($rate)
    ) {
        continue;
    }


    $dailyTrend[] = [

        "date" => $date,

        "label" => date(
            "M j",
            strtotime($date)
        ),

        "attendance_rate" =>
            ((float)$rate) * 100

    ];
}


// ============================================================
// 7. STUDENT RECOMMENDATIONS
// ============================================================

$recommendationFile =
    $reportsPath
    . DIRECTORY_SEPARATOR
    . "student_recommendations.csv";


$recommendationRows =
    readCsvRows(
        $recommendationFile
    );


// ============================================================
// 8. RISK COUNTS
// ============================================================

$riskCounts = [

    "High Risk" => 0,
    "Moderate Risk" => 0,
    "Low Risk" => 0

];


foreach ($recommendationRows as $row) {

    $risk =
        $row["Predicted_Risk"]
        ?? "";

    if (isset($riskCounts[$risk])) {
        $riskCounts[$risk]++;
    }
}


$highRiskCount =
    $riskCounts["High Risk"];

$moderateRiskCount =
    $riskCounts["Moderate Risk"];

$lowRiskCount =
    $riskCounts["Low Risk"];


// ============================================================
// 9. RECOMMENDATION PRIORITIES
// ============================================================

$priorityCounts = [

    "High" => 0,
    "Medium" => 0,
    "Routine" => 0

];


foreach ($recommendationRows as $row) {

    $priority =
        $row["Recommendation_Priority"]
        ?? "";

    if (isset($priorityCounts[$priority])) {
        $priorityCounts[$priority]++;
    }
}


$highPriorityCount =
    $priorityCounts["High"];

$mediumPriorityCount =
    $priorityCounts["Medium"];

$routinePriorityCount =
    $priorityCounts["Routine"];


// ============================================================
// 10. TOTAL RECOMMENDATION RECORDS
// ============================================================

$totalRecommendationStudents =
    count($recommendationRows);


// ============================================================
// 11. DEVELOPMENT FLAG
// ============================================================

$isSyntheticDevelopment = true; 