<?php

require_once __DIR__ . "/includes/auth.php";

/*
|--------------------------------------------------------------------------
| AI: Attend Mo - Attendance Records
|--------------------------------------------------------------------------
| Reads cleaned attendance records generated by the Python pipeline.
| Current records are synthetic development data.
|--------------------------------------------------------------------------
*/


// ============================================================
// 1. FILE PATH
// ============================================================

$projectRoot = dirname(__DIR__);

$attendanceFile =
    $projectRoot
    . DIRECTORY_SEPARATOR
    . "data"
    . DIRECTORY_SEPARATOR
    . "attendance_cleaned.csv";


// ============================================================
// 2. PAGINATION SETTINGS
// ============================================================

$recordsPerPage = 25;

$currentPage =
    isset($_GET["page"])
        ? max(1, (int)$_GET["page"])
        : 1;

$offset =
    ($currentPage - 1)
    * $recordsPerPage;


// ============================================================
// 3. FILTER VALUES
// ============================================================

$searchStudent =
    trim($_GET["student"] ?? "");

$filterGrade =
    trim($_GET["grade"] ?? "");

$filterSection =
    trim($_GET["section"] ?? "");

$filterSubject =
    trim($_GET["subject"] ?? "");

$filterStatus =
    trim($_GET["status"] ?? "");

$filterDate =
    trim($_GET["date"] ?? "");


// ============================================================
// 4. DATA STORAGE
// ============================================================

$attendanceRecords = [];

$totalMatchingRecords = 0;

$gradeOptions = [];
$sectionOptions = [];
$subjectOptions = [];

$fileError = "";


// ============================================================
// 5. READ ATTENDANCE CSV
// ============================================================

if (!file_exists($attendanceFile)) {

    $fileError =
        "attendance_cleaned.csv was not found.";

} else {

    $handle =
        fopen(
            $attendanceFile,
            "r"
        );


    if ($handle === false) {

        $fileError =
            "Unable to open attendance data.";

    } else {

        $headers =
            fgetcsv($handle);


        if ($headers !== false) {

            // Remove possible UTF-8 BOM

            if (isset($headers[0])) {

                $headers[0] =
                    preg_replace(
                        '/^\xEF\xBB\xBF/',
                        '',
                        trim($headers[0])
                    );
            }


            $headers =
                array_map(
                    "trim",
                    $headers
                );


            while (
                ($data = fgetcsv($handle))
                !== false
            ) {

                if (
                    count($data)
                    !==
                    count($headers)
                ) {
                    continue;
                }


                $row =
                    array_combine(
                        $headers,
                        $data
                    );


                if ($row === false) {
                    continue;
                }


                $row =
                    array_map(
                        "trim",
                        $row
                    );


                // --------------------------------------------
                // Collect available filter options
                // --------------------------------------------

                if (
                    !empty(
                        $row["Grade_Level"]
                    )
                ) {

                    $gradeOptions[
                        $row["Grade_Level"]
                    ] = true;
                }


                if (
                    !empty(
                        $row["Section"]
                    )
                ) {

                    $sectionOptions[
                        $row["Section"]
                    ] = true;
                }


                if (
                    !empty(
                        $row["Subject"]
                    )
                ) {

                    $subjectOptions[
                        $row["Subject"]
                    ] = true;
                }


                // --------------------------------------------
                // SEARCH STUDENT
                // --------------------------------------------

                if (
                    $searchStudent !== ""
                    &&
                    stripos(
                        $row["Student_ID"],
                        $searchStudent
                    ) === false
                ) {
                    continue;
                }


                // --------------------------------------------
                // GRADE FILTER
                // --------------------------------------------

                if (
                    $filterGrade !== ""
                    &&
                    $row["Grade_Level"]
                    !==
                    $filterGrade
                ) {
                    continue;
                }


                // --------------------------------------------
                // SECTION FILTER
                // --------------------------------------------

                if (
                    $filterSection !== ""
                    &&
                    $row["Section"]
                    !==
                    $filterSection
                ) {
                    continue;
                }


                // --------------------------------------------
                // SUBJECT FILTER
                // --------------------------------------------

                if (
                    $filterSubject !== ""
                    &&
                    $row["Subject"]
                    !==
                    $filterSubject
                ) {
                    continue;
                }


                // --------------------------------------------
                // STATUS FILTER
                // --------------------------------------------

                if (
                    $filterStatus !== ""
                    &&
                    $row["Attendance_Status"]
                    !==
                    $filterStatus
                ) {
                    continue;
                }


                // --------------------------------------------
                // DATE FILTER
                // --------------------------------------------

                if (
                    $filterDate !== ""
                    &&
                    $row["Date"]
                    !==
                    $filterDate
                ) {
                    continue;
                }


                // --------------------------------------------
                // MATCHED RECORD
                // --------------------------------------------

                $totalMatchingRecords++;


                if (
                    $totalMatchingRecords
                    >
                    $offset
                    &&
                    count(
                        $attendanceRecords
                    )
                    <
                    $recordsPerPage
                ) {

                    $attendanceRecords[] =
                        $row;
                }
            }
        }


        fclose($handle);
    }
}


// ============================================================
// 6. SORT FILTER OPTIONS
// ============================================================

$gradeOptions =
    array_keys(
        $gradeOptions
    );

$sectionOptions =
    array_keys(
        $sectionOptions
    );

$subjectOptions =
    array_keys(
        $subjectOptions
    );


sort(
    $gradeOptions,
    SORT_NATURAL
);

sort(
    $sectionOptions,
    SORT_NATURAL
);

sort(
    $subjectOptions,
    SORT_NATURAL
);


// ============================================================
// 7. PAGINATION
// ============================================================

$totalPages =
    max(
        1,
        (int)ceil(
            $totalMatchingRecords
            /
            $recordsPerPage
        )
    );


if ($currentPage > $totalPages) {

    $currentPage =
        $totalPages;
}


// ============================================================
// 8. PAGINATION URL HELPER
// ============================================================

function attendancePageUrl($page)
{
    $query = $_GET;

    $query["page"] = $page;

    return
        "attendance.php?"
        .
        http_build_query(
            $query
        );
}


// ============================================================
// 9. DISPLAY RANGE
// ============================================================

if ($totalMatchingRecords > 0) {

    $displayStart =
        $offset + 1;

    $displayEnd =
        min(
            $offset
            +
            $recordsPerPage,

            $totalMatchingRecords
        );

} else {

    $displayStart = 0;
    $displayEnd = 0;
}

?>

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >

    <title>
        AI: Attend Mo | Attendance
    </title>

    <link
        rel="stylesheet"
        href="assets/css/style.css"
    >

</head>


<body class="dashboard-body">

<div class="app-layout">


    <!-- =====================================================
         SIDEBAR
         ===================================================== -->

    <aside class="sidebar">

        <div class="sidebar-brand">

            <h2>
                AI: Attend Mo
            </h2>

            <p>
                Attendance Analytics
            </p>

        </div>


        <nav class="sidebar-nav">

            <a
                href="dashboard.php"
                class="nav-link"
            >
                Dashboard
            </a>

            <a
                href="attendance.php"
                class="nav-link active"
            >
                Attendance
            </a>

            <a
                href="analytics.php"
                class="nav-link"
            >
                Analytics
            </a>

            <a
                href="prediction.php"
                class="nav-link"
            >
                Risk Prediction
            </a>

            <a
                href="recommendations.php"
                class="nav-link"
            >
                Recommendations
            </a>

            <a
                href="reports.php"
                class="nav-link"
            >
                Reports
            </a>

            <a
                href="users.php"
                class="nav-link"
            >
                Users
            </a>
            <a
                href="logout.php"
                class="nav-link"
            >
                Logout
            </a>

        </nav>


        <div class="sidebar-footer">

            <p>
                Echague National High School
            </p>

        </div>

    </aside>


    <!-- =====================================================
         MAIN CONTENT
         ===================================================== -->

    <main class="main-content">


        <!-- TOP BAR -->

        <header class="topbar">

            <div>

                <p class="page-label">
                    ATTENDANCE MANAGEMENT
                </p>

                <h1>
                    Attendance Records
                </h1>

            </div>


            <div class="topbar-user">

                <div class="user-avatar">
                    A
                </div>

                <div>

                    <strong>
                        Authorized User
                    </strong>

                    <span>
                        System Access
                    </span>

                </div>

            </div>

        </header>


        <!-- DEVELOPMENT NOTICE -->

        <section class="development-notice">

            <strong>
                Synthetic Development Data
            </strong>

            <p>
                These attendance records are currently
                generated synthetic records used for
                system development and testing.
            </p>

        </section>


        <!-- =================================================
             FILTER PANEL
             ================================================= -->

        <section class="attendance-filter-panel">

            <div class="attendance-filter-header">

                <div>

                    <p class="panel-label">
                        SEARCH & FILTER
                    </p>

                    <h3>
                        Find Attendance Records
                    </h3>

                </div>


                <a
                    href="attendance.php"
                    class="clear-filter-link"
                >
                    Clear Filters
                </a>

            </div>


            <form
                method="GET"
                action="attendance.php"
                class="attendance-filter-form"
            >


                <!-- STUDENT -->

                <div class="attendance-filter-group">

                    <label for="student">
                        Student ID
                    </label>

                    <input
                        type="text"
                        id="student"
                        name="student"
                        placeholder="Search Student ID"
                        value="<?php
                        echo htmlspecialchars(
                            $searchStudent
                        );
                        ?>"
                    >

                </div>


                <!-- GRADE -->

                <div class="attendance-filter-group">

                    <label for="grade">
                        Grade Level
                    </label>

                    <select
                        id="grade"
                        name="grade"
                    >

                        <option value="">
                            All Grades
                        </option>


                        <?php foreach ($gradeOptions as $grade): ?>

                            <option
                                value="<?php echo htmlspecialchars($grade); ?>"
                                <?php
                                echo
                                    $filterGrade === $grade
                                        ? "selected"
                                        : "";
                                ?>
                            >
                                <?php
                                echo htmlspecialchars(
                                    $grade
                                );
                                ?>
                            </option>

                        <?php endforeach; ?>

                    </select>

                </div>


                <!-- SECTION -->

                <div class="attendance-filter-group">

                    <label for="section">
                        Section
                    </label>

                    <select
                        id="section"
                        name="section"
                    >

                        <option value="">
                            All Sections
                        </option>


                        <?php foreach ($sectionOptions as $section): ?>

                            <option
                                value="<?php echo htmlspecialchars($section); ?>"
                                <?php
                                echo
                                    $filterSection === $section
                                        ? "selected"
                                        : "";
                                ?>
                            >
                                <?php
                                echo htmlspecialchars(
                                    $section
                                );
                                ?>
                            </option>

                        <?php endforeach; ?>

                    </select>

                </div>


                <!-- SUBJECT -->

                <div class="attendance-filter-group">

                    <label for="subject">
                        Subject
                    </label>

                    <select
                        id="subject"
                        name="subject"
                    >

                        <option value="">
                            All Subjects
                        </option>


                        <?php foreach ($subjectOptions as $subject): ?>

                            <option
                                value="<?php echo htmlspecialchars($subject); ?>"
                                <?php
                                echo
                                    $filterSubject === $subject
                                        ? "selected"
                                        : "";
                                ?>
                            >
                                <?php
                                echo htmlspecialchars(
                                    $subject
                                );
                                ?>
                            </option>

                        <?php endforeach; ?>

                    </select>

                </div>


                <!-- STATUS -->

                <div class="attendance-filter-group">

                    <label for="status">
                        Status
                    </label>

                    <select
                        id="status"
                        name="status"
                    >

                        <option value="">
                            All Status
                        </option>

                        <option
                            value="Present"
                            <?php
                            echo
                                $filterStatus === "Present"
                                    ? "selected"
                                    : "";
                            ?>
                        >
                            Present
                        </option>

                        <option
                            value="Absent"
                            <?php
                            echo
                                $filterStatus === "Absent"
                                    ? "selected"
                                    : "";
                            ?>
                        >
                            Absent
                        </option>

                    </select>

                </div>


                <!-- DATE -->

                <div class="attendance-filter-group">

                    <label for="date">
                        Date
                    </label>

                    <input
                        type="date"
                        id="date"
                        name="date"
                        value="<?php
                        echo htmlspecialchars(
                            $filterDate
                        );
                        ?>"
                    >

                </div>


                <!-- BUTTON -->

                <div class="attendance-filter-action">

                    <button
                        type="submit"
                        class="attendance-filter-button"
                    >
                        Apply Filters
                    </button>

                </div>


            </form>

        </section>


        <!-- =================================================
             RECORDS PANEL
             ================================================= -->

        <section class="attendance-table-panel">


            <div class="attendance-table-header">

                <div>

                    <p class="panel-label">
                        CLEAN ATTENDANCE DATA
                    </p>

                    <h3>
                        Attendance Records
                    </h3>

                </div>


                <div class="attendance-result-count">

                    <?php
                    echo number_format(
                        $totalMatchingRecords
                    );
                    ?>

                    record<?php
                    echo
                        $totalMatchingRecords === 1
                            ? ""
                            : "s";
                    ?>

                </div>

            </div>


            <?php if ($fileError !== ""): ?>

                <div class="attendance-error">

                    <?php
                    echo htmlspecialchars(
                        $fileError
                    );
                    ?>

                </div>


            <?php elseif (empty($attendanceRecords)): ?>

                <div class="attendance-empty">

                    <strong>
                        No attendance records found.
                    </strong>

                    <p>
                        Try changing or clearing your filters.
                    </p>

                </div>


            <?php else: ?>


                <div class="attendance-table-wrapper">

                    <table class="attendance-table">

                        <thead>

                            <tr>

                                <th>
                                    Student ID
                                </th>

                                <th>
                                    Grade Level
                                </th>

                                <th>
                                    Section
                                </th>

                                <th>
                                    Subject
                                </th>

                                <th>
                                    Date
                                </th>

                                <th>
                                    Time
                                </th>

                                <th>
                                    Status
                                </th>

                            </tr>

                        </thead>


                        <tbody>

                            <?php foreach ($attendanceRecords as $record): ?>

                                <tr>

                                    <td class="student-id-cell">
                                        <?php
                                        echo htmlspecialchars(
                                            $record["Student_ID"]
                                        );
                                        ?>
                                    </td>


                                    <td>
                                        <?php
                                        echo htmlspecialchars(
                                            $record["Grade_Level"]
                                        );
                                        ?>
                                    </td>


                                    <td>
                                        <?php
                                        echo htmlspecialchars(
                                            $record["Section"]
                                        );
                                        ?>
                                    </td>


                                    <td>
                                        <?php
                                        echo htmlspecialchars(
                                            $record["Subject"]
                                        );
                                        ?>
                                    </td>


                                    <td>
                                        <?php
                                        echo htmlspecialchars(
                                            $record["Date"]
                                        );
                                        ?>
                                    </td>


                                    <td>
                                        <?php
                                        echo htmlspecialchars(
                                            $record["Time"]
                                        );
                                        ?>
                                    </td>


                                    <td>

                                        <?php

                                        $status =
                                            $record[
                                                "Attendance_Status"
                                            ];

                                        $statusClass =
                                            strtolower(
                                                $status
                                            );

                                        ?>

                                        <span
                                            class="attendance-status <?php echo htmlspecialchars($statusClass); ?>"
                                        >
                                            <?php
                                            echo htmlspecialchars(
                                                $status
                                            );
                                            ?>
                                        </span>

                                    </td>

                                </tr>

                            <?php endforeach; ?>

                        </tbody>

                    </table>

                </div>


                <!-- =========================================
                     PAGINATION
                     ========================================= -->

                <div class="attendance-pagination">


                    <div class="pagination-summary">

                        Showing

                        <strong>
                            <?php echo $displayStart; ?>
                        </strong>

                        –

                        <strong>
                            <?php echo $displayEnd; ?>
                        </strong>

                        of

                        <strong>
                            <?php
                            echo number_format(
                                $totalMatchingRecords
                            );
                            ?>
                        </strong>

                    </div>


                    <div class="pagination-buttons">


                        <?php if ($currentPage > 1): ?>

                            <a
                                href="<?php
                                echo htmlspecialchars(
                                    attendancePageUrl(
                                        $currentPage - 1
                                    )
                                );
                                ?>"
                                class="pagination-button"
                            >
                                Previous
                            </a>

                        <?php endif; ?>


                        <span class="pagination-current">

                            Page

                            <strong>
                                <?php
                                echo $currentPage;
                                ?>
                            </strong>

                            of

                            <strong>
                                <?php
                                echo $totalPages;
                                ?>
                            </strong>

                        </span>


                        <?php if ($currentPage < $totalPages): ?>

                            <a
                                href="<?php
                                echo htmlspecialchars(
                                    attendancePageUrl(
                                        $currentPage + 1
                                    )
                                );
                                ?>"
                                class="pagination-button"
                            >
                                Next
                            </a>

                        <?php endif; ?>


                    </div>

                </div>


            <?php endif; ?>


        </section>


    </main>

</div>

</body>

</html>