<?php

require_once __DIR__ . "/includes/auth.php";

/*
|--------------------------------------------------------------------------
| AI: Attend Mo - Reports Module
|--------------------------------------------------------------------------
| Displays analytical reports generated by the Python pipeline.
|--------------------------------------------------------------------------
*/

require_once __DIR__
    . "/includes/report_data.php";


// ============================================================
// 1. REPORT CATALOG
// ============================================================

$reportCatalog = [

    "Attendance Reports" => [

        "overall_attendance_summary.csv" => [
            "title" => "Overall Attendance Summary",
            "description" => "Overall students, attendance records, present, absent, attendance rate, and absence rate."
        ],

        "attendance_by_grade.csv" => [
            "title" => "Attendance by Grade",
            "description" => "Attendance and absence rates grouped by grade level."
        ],

        "attendance_by_section.csv" => [
            "title" => "Attendance by Section",
            "description" => "Attendance summary for each grade and section."
        ],

        "attendance_by_subject.csv" => [
            "title" => "Attendance by Subject",
            "description" => "Attendance and absence rates grouped by subject."
        ],

        "daily_attendance_trend.csv" => [
            "title" => "Daily Attendance Trend",
            "description" => "Daily attendance sessions, present records, absences, and attendance rates."
        ],

        "monthly_attendance_trend.csv" => [
            "title" => "Monthly Attendance Trend",
            "description" => "Monthly historical attendance trend."
        ],

        "frequently_absent_students.csv" => [
            "title" => "Frequently Absent Students",
            "description" => "Ranked students with higher observed absence counts."
        ]
    ],


    "Diagnostic Reports" => [

        "diagnostic_student_patterns.csv" => [
            "title" => "Student Absence Patterns",
            "description" => "Student-level recurring and frequent absence patterns."
        ],

        "diagnostic_weekly_patterns.csv" => [
            "title" => "Weekly Absence Patterns",
            "description" => "Weekly absence behavior and recurrence."
        ],

        "diagnostic_weekday_patterns.csv" => [
            "title" => "Weekday Absence Patterns",
            "description" => "Attendance and absence patterns according to day of the week."
        ],

        "diagnostic_grade_patterns.csv" => [
            "title" => "Grade Diagnostic Patterns",
            "description" => "Diagnostic attendance summary grouped by grade level."
        ],

        "diagnostic_section_patterns.csv" => [
            "title" => "Section Diagnostic Patterns",
            "description" => "Diagnostic attendance summary grouped by grade and section."
        ],

        "diagnostic_subject_patterns.csv" => [
            "title" => "Subject Diagnostic Patterns",
            "description" => "Diagnostic attendance summary grouped by subject."
        ]
    ],


    "Inferential Reports" => [

        "inferential_results.csv" => [
            "title" => "Inferential Analysis Results",
            "description" => "Statistical tests, p-values, decisions, and interpretations."
        ],

        "inferential_assumption_checks.csv" => [
            "title" => "Inferential Assumption Checks",
            "description" => "Normality and variance assumption checks used during statistical analysis."
        ],

        "subject_posthoc_results.csv" => [
            "title" => "Subject Post-hoc Results",
            "description" => "Pairwise subject comparisons after the significant Friedman test."
        ]
    ],


    "Predictive Reports" => [

        "decision_tree_metrics.csv" => [
            "title" => "Decision Tree Metrics",
            "description" => "Accuracy, precision, recall, F1-score, and train-test performance."
        ],

        "decision_tree_confusion_matrix.csv" => [
            "title" => "Confusion Matrix",
            "description" => "Actual versus predicted absenteeism-risk classifications."
        ],

        "decision_tree_classification_report.csv" => [
            "title" => "Classification Report",
            "description" => "Detailed class-level Decision Tree evaluation metrics."
        ],

        "decision_tree_feature_importance.csv" => [
            "title" => "Feature Importance",
            "description" => "Relative importance of attendance-related predictive features."
        ],

        "decision_tree_test_predictions.csv" => [
            "title" => "Test Predictions",
            "description" => "Student-level model predictions from the reserved synthetic test set."
        ],

        "decision_tree_cross_validation.csv" => [
            "title" => "Cross-Validation Results",
            "description" => "Five-fold model validation results."
        ],

        "decision_tree_cross_validation_summary.csv" => [
            "title" => "Cross-Validation Summary",
            "description" => "Mean validation metrics and model stability summary."
        ]
    ],


    "Decision-Support Reports" => [

        "student_recommendations.csv" => [
            "title" => "Student Recommendations",
            "description" => "Risk-based decision-support recommendations and recommendation basis."
        ]
    ],


    "Data Preparation Reports" => [

        "cleaning_report.csv" => [
            "title" => "Data Cleaning Report",
            "description" => "Summary of missing values, invalid records, duplicates, and cleaned records."
        ],

        "feature_engineering_report.csv" => [
            "title" => "Feature Engineering Report",
            "description" => "Summary of engineered attendance-related analytical variables."
        ],

        "rejected_records.csv" => [
            "title" => "Rejected Records",
            "description" => "Attendance records excluded during data cleaning."
        ]
    ]
];


// ============================================================
// 2. CREATE ALLOWLIST
// ============================================================

$allowedReports = [];

foreach ($reportCatalog as $category => $reports) {

    foreach ($reports as $fileName => $details) {

        $allowedReports[$fileName] = $details;
    }
}


// ============================================================
// 3. FILE INFORMATION HELPER
// ============================================================

function reportFileInfo(
    $reportsPath,
    $fileName
) {
    $filePath =
        $reportsPath
        . DIRECTORY_SEPARATOR
        . $fileName;

    if (!file_exists($filePath)) {

        return [
            "exists" => false,
            "size" => "—",
            "rows" => "—"
        ];
    }


    $sizeBytes =
        filesize($filePath);


    if ($sizeBytes >= 1024 * 1024) {

        $size =
            number_format(
                $sizeBytes / (1024 * 1024),
                2
            )
            . " MB";

    } elseif ($sizeBytes >= 1024) {

        $size =
            number_format(
                $sizeBytes / 1024,
                1
            )
            . " KB";

    } else {

        $size =
            $sizeBytes
            . " B";
    }


    $rows = 0;

    $handle =
        fopen(
            $filePath,
            "r"
        );


    if ($handle !== false) {

        // Skip header
        fgetcsv($handle);

        while (
            fgetcsv($handle)
            !== false
        ) {

            $rows++;
        }

        fclose($handle);
    }


    return [
        "exists" => true,
        "size" => $size,
        "rows" => $rows
    ];
}


// ============================================================
// 4. PREVIEW SELECTED REPORT
// ============================================================

$previewFile =
    basename(
        $_GET["preview"] ?? ""
    );


$previewTitle = "";
$previewRows = [];
$previewHeaders = [];


if (
    $previewFile !== ""
    &&
    isset(
        $allowedReports[$previewFile]
    )
) {

    $previewPath =
        $reportsPath
        . DIRECTORY_SEPARATOR
        . $previewFile;


    if (file_exists($previewPath)) {

        $previewRows =
            readCsvRows(
                $previewPath
            );


        if (!empty($previewRows)) {

            $previewHeaders =
                array_keys(
                    $previewRows[0]
                );
        }


        $previewTitle =
            $allowedReports[
                $previewFile
            ]["title"];
    }
}


// Limit browser preview
$previewRows =
    array_slice(
        $previewRows,
        0,
        50
    );

?>

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >

    <title>
        AI: Attend Mo | Reports
    </title>

    <link
        rel="stylesheet"
        href="assets/css/style.css"
    >

</head>


<body class="dashboard-body">

<div class="app-layout">


    <!-- SIDEBAR -->

    <aside class="sidebar">

        <div class="sidebar-brand">

            <h2>
                AI: Attend Mo
            </h2>

            <p>
                Attendance Analytics
            </p>

        </div>


        <nav class="sidebar-nav">

            <a
                href="dashboard.php"
                class="nav-link"
            >
                Dashboard
            </a>

            <a
                href="attendance.php"
                class="nav-link"
            >
                Attendance
            </a>

            <a
                href="analytics.php"
                class="nav-link"
            >
                Analytics
            </a>

            <a
                href="prediction.php"
                class="nav-link"
            >
                Risk Prediction
            </a>

            <a
                href="recommendations.php"
                class="nav-link"
            >
                Recommendations
            </a>

            <a
                href="reports.php"
                class="nav-link active"
            >
                Reports
            </a>

            <a
                href="users.php"
                class="nav-link"
            >
                Users
            </a>
            <a
                href="logout.php"
                class="nav-link"
            >
                Logout
            </a>

        </nav>


        <div class="sidebar-footer">

            <p>
                Echague National High School
            </p>

        </div>

    </aside>


    <!-- MAIN -->

    <main class="main-content">


        <!-- TOPBAR -->

        <header class="topbar">

            <div>

                <p class="page-label">
                    SYSTEM REPORTS
                </p>

                <h1>
                    Reports
                </h1>

            </div>


            <div class="topbar-user">

                <div class="user-avatar">
                    A
                </div>

                <div>

                    <strong>
                        Authorized User
                    </strong>

                    <span>
                        System Access
                    </span>

                </div>

            </div>

        </header>


        <!-- NOTICE -->

        <section class="development-notice">

            <strong>
                Synthetic Development Reports
            </strong>

            <p>
                Reports currently contain synthetic
                system-development results. They must not be
                interpreted as actual findings from Echague
                National High School.
            </p>

        </section>


        <!-- =================================================
             REPORT CATALOG
             ================================================= -->

        <?php foreach ($reportCatalog as $category => $reports): ?>

            <section class="reports-category">


                <div class="reports-category-header">

                    <div>

                        <p class="panel-label">
                            GENERATED OUTPUTS
                        </p>

                        <h2>
                            <?php
                            echo htmlspecialchars(
                                $category
                            );
                            ?>
                        </h2>

                    </div>


                    <span class="reports-category-count">

                        <?php
                        echo count(
                            $reports
                        );
                        ?>

                        report<?php
                        echo
                            count($reports) === 1
                                ? ""
                                : "s";
                        ?>

                    </span>

                </div>


                <div class="reports-grid">


                    <?php foreach ($reports as $fileName => $details): ?>

                        <?php

                        $info =
                            reportFileInfo(
                                $reportsPath,
                                $fileName
                            );

                        ?>


                        <article
                            class="report-card
                            <?php
                            echo
                                $info["exists"]
                                    ? ""
                                    : "missing";
                            ?>"
                        >


                            <div class="report-card-top">


                                <div class="report-file-icon">
                                    CSV
                                </div>


                                <span
                                    class="report-status
                                    <?php
                                    echo
                                        $info["exists"]
                                            ? "available"
                                            : "missing";
                                    ?>"
                                >

                                    <?php
                                    echo
                                        $info["exists"]
                                            ? "Available"
                                            : "Not Generated";
                                    ?>

                                </span>


                            </div>


                            <h3>

                                <?php
                                echo htmlspecialchars(
                                    $details["title"]
                                );
                                ?>

                            </h3>


                            <p>

                                <?php
                                echo htmlspecialchars(
                                    $details[
                                        "description"
                                    ]
                                );
                                ?>

                            </p>


                            <div class="report-metadata">

                                <div>

                                    <span>
                                        Records
                                    </span>

                                    <strong>
                                        <?php
                                        echo htmlspecialchars(
                                            (string)$info[
                                                "rows"
                                            ]
                                        );
                                        ?>
                                    </strong>

                                </div>


                                <div>

                                    <span>
                                        Size
                                    </span>

                                    <strong>
                                        <?php
                                        echo htmlspecialchars(
                                            $info[
                                                "size"
                                            ]
                                        );
                                        ?>
                                    </strong>

                                </div>

                            </div>


                            <div class="report-actions">


                                <?php if ($info["exists"]): ?>


                                    <a
                                        href="reports.php?preview=<?php
                                        echo urlencode(
                                            $fileName
                                        );
                                        ?>#report-preview"
                                        class="report-button secondary"
                                    >
                                        Preview
                                    </a>


                                    <a
                                        href="report_download.php?file=<?php
                                        echo urlencode(
                                            $fileName
                                        );
                                        ?>"
                                        class="report-button primary"
                                    >
                                        Download CSV
                                    </a>


                                <?php else: ?>


                                    <span
                                        class="report-button disabled"
                                    >
                                        Unavailable
                                    </span>


                                <?php endif; ?>


                            </div>


                        </article>


                    <?php endforeach; ?>


                </div>


            </section>


        <?php endforeach; ?>


        <!-- =================================================
             PREVIEW
             ================================================= -->

        <?php if ($previewFile !== ""): ?>

            <section
                class="report-preview-card"
                id="report-preview"
            >


                <div class="report-preview-header">

                    <div>

                        <p class="panel-label">
                            REPORT PREVIEW
                        </p>

                        <h2>
                            <?php
                            echo htmlspecialchars(
                                $previewTitle
                                ?: "Report"
                            );
                            ?>
                        </h2>

                        <p>
                            Showing up to the first 50
                            report records.
                        </p>

                    </div>


                    <div class="report-preview-actions">


                        <a
                            href="reports.php"
                            class="report-button secondary"
                        >
                            Close Preview
                        </a>


                        <?php if (
                            isset(
                                $allowedReports[
                                    $previewFile
                                ]
                            )
                        ): ?>

                            <a
                                href="report_download.php?file=<?php
                                echo urlencode(
                                    $previewFile
                                );
                                ?>"
                                class="report-button primary"
                            >
                                Download CSV
                            </a>

                        <?php endif; ?>


                    </div>

                </div>


                <?php if (
                    empty($previewRows)
                    ||
                    empty($previewHeaders)
                ): ?>


                    <div class="analytics-v2-empty">

                        No preview data available.

                    </div>


                <?php else: ?>


                    <div class="report-preview-table-wrapper">


                        <table class="report-preview-table">


                            <thead>

                                <tr>


                                    <?php foreach ($previewHeaders as $header): ?>

                                        <th>

                                            <?php
                                            echo htmlspecialchars(
                                                str_replace(
                                                    "_",
                                                    " ",
                                                    $header
                                                )
                                            );
                                            ?>

                                        </th>

                                    <?php endforeach; ?>


                                </tr>

                            </thead>


                            <tbody>


                                <?php foreach ($previewRows as $row): ?>

                                    <tr>


                                        <?php foreach ($previewHeaders as $header): ?>

                                            <td>

                                                <?php
                                                echo htmlspecialchars(
                                                    $row[
                                                        $header
                                                    ]
                                                    ?? "—"
                                                );
                                                ?>

                                            </td>

                                        <?php endforeach; ?>


                                    </tr>

                                <?php endforeach; ?>


                            </tbody>


                        </table>


                    </div>


                <?php endif; ?>


            </section>


        <?php endif; ?>


        <div class="analytics-v2-footnote">

            <strong>
                Report Handling:
            </strong>

            The Reports module reads files generated by the
            Python analytics pipeline. Updating and rerunning
            the analytics scripts will update the corresponding
            reports displayed by the system.

        </div>


    </main>

</div>

</body>

</html>